# Generated by Django 4.2.8 on 2023-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0002_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
