# Generated by Django 4.2.9 on 2024-01-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0003_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
            ],
        ),
    ]
