# Generated by Django 4.2.9 on 2024-01-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='pos_server.menu'),
            preserve_default=False,
        ),
    ]
