# Generated by Django 4.2.9 on 2024-01-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0005_dish_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
