# Generated by Django 4.2.9 on 2024-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0006_order_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='done',
            new_name='bar_done',
        ),
        migrations.AddField(
            model_name='dish',
            name='station',
            field=models.CharField(default='kitchen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_done',
            field=models.BooleanField(default=False),
        ),
    ]
