# Generated by Django 4.2.9 on 2024-01-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0011_ingredient_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='ingredients',
        ),
    ]
