# Generated by Django 4.2.9 on 2024-01-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0012_remove_component_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_server.component')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_server.dish')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_server.component')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_server.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='ingredients',
            field=models.ManyToManyField(through='pos_server.ComponentIngredient', to='pos_server.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='components',
            field=models.ManyToManyField(through='pos_server.DishComponent', to='pos_server.component'),
        ),
    ]
