# Generated by Django 4.2.9 on 2024-01-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0017_alter_order_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='accent_1',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='menu',
            name='accent_2',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='menu',
            name='accent_3',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='menu',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='menu',
            name='footer_image',
            field=models.ImageField(null=True, upload_to='files/menu_decorations'),
        ),
        migrations.AddField(
            model_name='menu',
            name='header_image',
            field=models.ImageField(null=True, upload_to='files/menu_decorations'),
        ),
    ]
