# Generated by Django 4.2.9 on 2024-01-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0019_menu_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage')], default='food', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='station',
            field=models.CharField(choices=[('bar', 'Bar'), ('kitchen', 'Kitchen'), ('gng', 'Grab & Go')], max_length=50),
        ),
    ]
