# Generated by Django 4.2.9 on 2024-01-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0021_remove_dish_type_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='force_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
