# Generated by Django 4.2.9 on 2024-02-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0024_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='inventory',
            field=models.FloatField(default=0, null=True),
        ),
    ]
