# Generated by Django 4.2.9 on 2024-02-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0027_component_self_crafting_ingredient_unlimited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='menu',
        ),
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ManyToManyField(related_name='dishes', to='pos_server.menu'),
        ),
    ]
