# Generated by Django 4.2.9 on 2024-02-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_recipe'),
        ('pos_server', '0028_remove_dish_menu_dish_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='inventory.recipe'),
        ),
    ]
