# Generated by Django 4.2.9 on 2024-02-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_recipe_original_yield'),
        ('pos_server', '0029_dish_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='component', to='inventory.recipe'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dish', to='inventory.recipe'),
        ),
    ]
