# Generated by Django 4.2.9 on 2024-02-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_server', '0022_component_force_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.FileField(null=True, upload_to='files/ingredient_receipts')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_server.ingredient')),
                ('update_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockupdate')),
            ],
        ),
    ]
