# Generated by Django 4.2.9 on 2024-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='original_yield',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
