# Generated by Django 5.0.3 on 2024-05-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='10385024465668656438786146353158', max_length=16)),
                ('email', models.CharField(max_length=64, null=True)),
                ('available_balance', models.FloatField(default=0)),
            ],
        ),
    ]
