# Generated by Django 5.0.3 on 2024-05-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPresets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='email',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='number',
            field=models.CharField(default='5168620657764885', max_length=16),
        ),
    ]
