# Generated by Django 5.0.3 on 2024-05-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0002_cardpresets_alter_giftcard_available_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='number',
            field=models.CharField(default='8622400065320414', max_length=16),
        ),
    ]
