# Generated by Django 5.0.3 on 2024-05-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0004_alter_giftcard_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardPresets',
            new_name='CardPreset',
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='number',
            field=models.CharField(default='1950753415937720', max_length=16),
        ),
    ]
