# Generated by Django 5.0.3 on 2024-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0006_cardpreset_image_alter_giftcard_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(null=True, upload_to='files/gift-cards/presets')),
            ],
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='number',
            field=models.CharField(default='3919309578959706', max_length=16),
        ),
    ]
